app/urls.py
from django.urls import path
from app.views import home, login_user, logout_user, register_user, customer, file_form

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/<role>', register_user, name='register'),
    path('customer/', customer, name='customer'),

    path('fform/', file_form, name='file-form'),
]

autoworld/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from orders.views import OrderCreateView, OrderDelete, OrderUpdate, orders_list, MyOrdersList, make_offer, MyOffersList, MyOrdersCustomerList, GetOffersListByOrderId, accept_offer
from django.urls import path, include


urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='orders create'),
    path('list/', orders_list, name='orders list'),
    path('my/', MyOrdersList.as_view(), name='my orders'),
    path('my/customer', MyOrdersCustomerList.as_view(), name='my orders customer'),
    path('offer/<int:order_id>', make_offer, name='make offer'),
    path('my/offers/', MyOffersList.as_view(), name='my offers'),
    path('getoffers/<int:order_id>', GetOffersListByOrderId.as_view(), name='get offers by order id'),
    path('accept/offer/<int:offer_id>', accept_offer, name='accept offer'),
    path('edit/<int:pk>', OrderUpdate.as_view(), name='edit order'),
    path('delete/<int:pk>', OrderDelete.as_view(), name='order delete'),

    # path('details/<int:pk>', OrderUpdate, name='order detail')
]

orders/models.py
from django.conf import settings
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse

class Order(models.Model):
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=CASCADE
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    description = models.TextField()

    # def get_absolute_url(self):
    #     return reverse('order-detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return self.description

class Offer(models.Model):
    order = models.ForeignKey(
        Order, on_delete=CASCADE
    )

    trader = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=CASCADE, blank=True, null=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    isAccepted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.order.description

orders/forms.py
from django.forms import ModelForm
from orders.models import Offer


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = ['price']

orders/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView
import orders
from orders.models import Offer, Order
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.models import User
from django.views.decorators.http import require_safe, require_POST
from orders.forms import OfferForm
from django.contrib.auth.mixins import LoginRequiredMixin


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    template_name = 'orders/create-order.html'
    fields = ('description',)
    success_url = '/'

    def form_valid(self, form):
        order = form.save(commit=False)
        order.customer = self.request.user
        self.object = order.save()
        return super().form_valid(form)


@require_safe
def orders_list(request):
    orders = Order.objects.all()
    my_offered_orders_ids = [
        offer.order.id for offer in Offer.objects.filter(trader=request.user)]
    context = {
        "orders": orders,
        "my_offered_orders_ids": my_offered_orders_ids
    }

    return render(request, 'orders/list-orders.html', context)


class MyOrdersList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'orders/list-orders.html'

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user)


def make_offer(request, order_id):
    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid:
            offer = form.save(commit=False)
            offer.order = Order.objects.get(id=order_id)
            offer.trader = request.user
            offer.save()
        return redirect('orders list')


class MyOffersList(LoginRequiredMixin, ListView):
    model = Offer
    template_name = 'orders/list-offers.html'

    def get_queryset(self):
        return Offer.objects.filter(trader=self.request.user)


class MyOrdersCustomerList(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'orders/list-orders-customer.html'

    def get_queryset(self):
        queryset = Order.objects.filter(customer=self.request.user)
        # queryset = Order.objects.filter(offer__order__customer=self.request.user)

        return queryset


class GetOffersListByOrderId(LoginRequiredMixin, ListView):
    model = Offer
    template_name = 'orders/list-offers-by-order.html'

    def get_queryset(self):
        return Offer.objects.filter(order__id=self.kwargs['order_id'])


@require_POST
def accept_offer(request, offer_id):
    offer = Offer.objects.get(id=offer_id)
    offer.isAccepted = True
    offer.save()
    return redirect('my orders customer')


class OrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    fields = ['description']
    template_name = 'orders/order-edit.html'
    success_url = reverse_lazy('my orders customer')



class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('my orders customer')
    template_name = 'orders/order-delete.html'

templates/orders/create-order.html
{% extends 'base.html' %}

{% block content %}
<h1>Create order</h1>
<form class="lo-ul" method="post" action="{% url 'orders create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button>Create</button>
</form>
{% endblock %}

templates/orders/list-offers-by-order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Offers for order: {{ object_list.all.0 }}</h1>
<ul>
    {% for offer in object_list %}
    <li class="lobo-li">
        {% if offer.isAccepted %}
        <img class="avatar" src="/media/{{ offer.trader.userprofile.profile_picture }}" />
            {{ offer.trader }} - ${{ offer.price }} - Accepted
        {% else %}
        <div class="card" style="width: 18rem;">
            <img class="avatar" src="/media/{{ offer.trader.userprofile.profile_picture }}" />
            <div class="card-body">
              <p class="card-text">Trader: {{ offer.trader }}</p>
              <p class="card-text">${{ offer.price }}</p>
            </div>
            <form action="{% url 'accept offer' offer.id %}" method="POST">
                {% csrf_token %}
                <button type="submit">Accept</button>
          </div>
        <!-- <img class="avatar" src="/media/{{ offer.trader.userprofile.profile_picture }}" />
            {{ offer.trader }} - ${{ offer.price }}
            <form action="{% url 'accept offer' offer.id %}" method="POST">
                {% csrf_token %}
                <button type="submit">Accept</button>
            </form> -->
        {% endif %}
    </li>
    {% empty %}
    <li>No orders yet.</li>
    {% endfor %}
</ul>
{% endblock %}

templates/orders/list-offers.html
{% extends 'base.html' %}

{% block content %}
<h1>My Offers</h1>
<ul class="lo-ul">
    {% for offer in object_list %}
    <li>
        {{ offer.order.description }} - ${{ offer.price }} 
        {% if offer.isAccepted %}
           - Accepted
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/orders/list-orders-customer.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
{% endblock head %}

{% block content %}
<h1>Orders</h1>
<ul>
    {% for order in object_list %}
    <li class="loc-li">
        <a href="{% url 'get offers by order id' order.id %}">
        <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <p>Description: {{ order.description }}</p>
          <p>Orders count: {{order.offer_set.count}}</p>
          <a href="{% url 'edit order' order.id %}">Edit</a>
          <a href="{% url 'order delete' order.id %}">Delete</a>
        </div>
      </div>
    </a>
    </li>
    {% empty %}
    <li>No orders yet.</li>
    {% endfor %}
</ul>
{% endblock %}

templates/orders/list-orders.html
{% extends 'base.html' %}

{% block content %}
<h1>Orders</h1>
<ul class="lo-ul">
    {% for order in orders %}
    <li>
        {% if order.id in my_offered_orders_ids %}
    <li>{{ order }} - Offer sent</li>
    {% else %}
    <form action="{% url 'make offer' order.id %}" method="POST">
        {% csrf_token %}
        {{ order }}
        <input id="price" name="price">
        <button type="submit" style="cursor: pointer;">
            submit
        </button>
    </form>
    </li>
    {% endif %}
    {% empty %}
    <li>No orders yet.</li>
    {% endfor %}
</ul>
{% endblock %}

templates/orders/order-delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete order: {{order}}</h1>
<form class="lo-ul" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ order }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

templates/orders/order-edit.html
{% extends 'base.html' %}

{% block content %}

<h1>Edit order: {{order}}</h1>
<form class="lo-ul" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}